### ISSUE TITLE
Module stability/compatibility

### ISSUE THREAD

**Issue by cboulanger** [ConnectedCommunities/humhub-modules-bulk_import#1]
Hello, 
came here from https://github.com/humhub/humhub/issues/721 . Thanks for creating this module! I would like to integrate this into an institutional HumHub installation, however, I would need to know the follwing:
- Stability: Is the module reasonably stable and tested?
- Compatibility: is it compatible with the current release and do you expect it to stay compatible with the 1.x line of Humhub?
- Maintenance: do you expect to be able to maintain/support the module, at least during the 1.x versions?

Thank you.

**Comment by benmag** [comment]
The module works as expected v1.0.0, so I expect it'd be compatible with v1.0.1 and every other Humhub minor release.

This module has been around since Humhub 0.x. The intention is to support the latest version of Humhub. Of course, pull requests welcomed and encouraged to help achieve this.

**Comment by cboulanger** [comment]
Thank you! I will report bugs if I notice any and will try to contribute if necessary and possible.
