### ISSUE TITLE
Updates for 1.10 ?

### ISSUE THREAD

**Issue by ghost** [ConnectedCommunities/humhub-modules-bulk_import#2]
Thanks for this. I was working on my own when 1.10 came out.

```
        // Hey why has this broken? Worked once?
        //Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: humhub\modules\user\models\User::group_id'
        // https://community.humhub.com/s/general-discussion/?wallEntryId=64426
        // Gone in 1.10 now using groups
        //  $userModel->group_id = 1;
```

That is the user group issue solved, sort of. I don't yet know whether a user must be connected to a group. Ie what are the database integrity rules if any.

I'm also getting an issue with 
`$profileModel->save();`

It fails to create the record.
I am about to embark of a debug mission. Hoping someone sees this issue and has a fast fix/answer.

(Hey we can always hope, right?) Thank you.

Two hours later...

$profileModel->save(**false**);
$userPasswordModel->save(**false**);

Bypassing validation worked for me (Add FALSE arg). Sorry but I am so new to this I cannot say if this is my issue or a change in the new release.  I also notice "transactional" logic which seems to me should be getting used here.

**Comment by benmag** [comment]
Yeah, looks like this is caused by the changes in 1.10. The module is compatible with the current official release of HumHub (1.0.1)

I will upgrade it when 1.10 is officially released.
