### ISSUE TITLE
Error during import: yii\base\UnknownPropertyException : group_id

### ISSUE THREAD

**Issue by cboulanger** [ConnectedCommunities/humhub-modules-bulk_import#5]
exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: humhub\modules\user\models\User::group_id' in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:197 Stack trace: #0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(272): yii\base\Component->__set('group_id', 1) #1 /var/www/humhub/protected/modules/bulk_import/controllers/MainController.php(67): yii\db\BaseActiveRecord->__set('group_id', 1) #2 /var/www/humhub/protected/modules/bulk_import/controllers/MainController.php(222): humhub\modules\bulk_import\controllers\MainController->registerUser(Array) #3 [internal function]: humhub\modules\bulk_import\controllers\MainController->actionUpload() #4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('upload', Array) #7 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('bulk_import/mai...', Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #9 /var/www/humhub/index.php(25): yii\base\Application->run() #10 {main}

**Comment by cboulanger** [comment]
I forgot the add the versions:  HumHub v1.1.1,, Bulk Import v1.0

**Comment by cboulanger** [comment]
Found the problem - it was an incompatibility issue. Upgrading to master fixed it.

**Comment by Oncle-BOB** [comment]
Hello, i have same problem and error. With fresh install Humhub 1.1.2 with Bulk Import 2.0 and you ?

**Comment by zx81sp** [comment]
Same here, humhub v1.1.1 with V1 fails, also v1.1.2 with V2.

**Comment by Oncle-BOB** [comment]
Alternative to run, remove these lines from /controllers/MainController.php
( line 67) 
> $ userModel-> group_id = $ data ['group_id'];

 and 
(line 218) 

> 'group_id' => $ group_id,

The correct group number must then be assigned in to the database.

**Comment by zx81sp** [comment]
Thanks, without that lines runs ok. Also there is a problem with localized chars like 'Ñ'.

Great module, it helps us so much!
