### ISSUE TITLE
Special characters do not get imported using mass import

### ISSUE THREAD

**Issue by guilzriel** [ConnectedCommunities/humhub-modules-bulk_import#6]
When using French characters to import, the system doesn't import the name correctly into the Profile table (first and last name both)

[example.txt](https://github.com/ConnectedCommunities/humhub-modules-bulk_import/files/764800/example.txt)

**Comment by boppy** [comment]
It is about encoding. Your file is Windows ANSI Encoded. As your file system, PHP and database should run in UTF8 you are facing this problem. You "just" need to convert your file (using notepad++, UltraEdit or any other "advanced" text editor).

With the [attached test file](https://github.com/ConnectedCommunities/humhub-modules-bulk_import/files/1266635/test-user-utf8.txt) I am even able to import chinese Characters (beside the french and german ones):
![utf8-rocks](https://user-images.githubusercontent.com/749141/29917478-6aadb47e-8e42-11e7-87a7-7760b63b0c95.PNG)
