### ISSUE TITLE
Space member import

### ISSUE THREAD

**Issue by abw1794guy** [ConnectedCommunities/humhub-modules-bulk_import#7]
Is it possible to import space members directly through CSV?

**Comment by gzriel-modus** [comment]
There's an import users module that you can use to do this. 

You can find it at:
Administration -> users -> import users tab

**Comment by guilzriel** [comment]
There's an import users module that you can use to do this.

You can find it at:
Administration -> users -> import users tab

**Comment by abw1794guy** [comment]
Thank you ! 
But I only see this ,
I didn't find  import users tab.
![3123](https://user-images.githubusercontent.com/8057681/27952734-e0c4a9b0-633b-11e7-8c3a-e695c19b87a4.PNG)
Which module are you talking about?
Version Humhub1.2.0

**Comment by benmag** [comment]
This bulk import module. You can set the Spaces a user should be imported into by providing `space_names`

Access the module by going to Admin Area > Bulk import
