### ISSUE TITLE
Unknown Property: Group ID

### ISSUE THREAD

**Issue by ryanp210** [ConnectedCommunities/humhub-modules-bulk_import#8]
Hi,

Thank you for your plugin! I am having some problems with your plugin and was hoping to get some help. 

**Problem:**
I am unable to upload a csv file without an error being returned. Usually the error reads " Setting unknown property"

**What I have tried:**
Using a csv you provided in an earlier support thread
making sure my csv contains the required fields as dictated in HumHub
checking sql database to see which fields might be off

**Screenshot:**
![screen shot 2017-10-09 at 1 24 36 pm](https://user-images.githubusercontent.com/32650074/31352694-4ac089ee-acf5-11e7-9357-4b2378a407cb.png)

**Hum Hub Version:**
1.2.2

**Links:**
Google Drive - https://goo.gl/51fwky (Web Archive File; Downloaded and uploaded the page to help)

If you have any suggestions please let me know. I am new to this so I am sure it is something simple I am missing. But thank you for the plugin and hope you have a great day! 

-Ryan

**Comment by glennzw** [comment]
I've got the same problem. If I remove the group_id property in the controllers/MainController.php file we get rid of this error, but then a new one of the CSV properties not being accessible. I'm not proficient in PHP, so it's a little hard to figure out what's going on, but seems to be a problem with how the CSV import is working.

```
//$userModel->group_id = $data['group_id'];
//$group_id = 1;
//      'group_id' => $group_id,
```

**Comment by glennzw** [comment]
The issue was that if 'space_names' was not included in the CSV file an exception was being thrown. Also the CSV parser if horrible for optional column names.

I submitted a pull request to fix both those issues. @ryanp210 you can grab it from my fork in the meantime: [glennzw/humhub-modules-bulk_import](https://github.com/glennzw/humhub-modules-bulk_import)

**Comment by ryanp210** [comment]
Great! Thank you for your help @glennzw !
